name: 'tmate-ubuntu'

# 设置触发器，包括定时触发和手动触发
on:
  # 定时触发，每 10 分钟触发一次
  # schedule:
    # - cron: '*/10 * * * *'
  # 手动触发，提供输入参数
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose tmate or ngrok mode' # 描述输入参数的用途
        required: false # 是否必须提供参数
        default: 'tmate' # 默认值为 'tmate'

# 定义名为 `ssh-debug` 的作业
jobs:
  ssh-debug:
    # 使用22.04版本的 Ubuntu 作为运行环境
    runs-on: ubuntu-22.04
    steps:
      # 第一步：检出代码仓库到工作目录
      - name: Checkout repository
        uses: actions/checkout@v2  # 使用官方的 checkout v2 动作

      # 第二步：选择模式并执行对应的脚本
      - name: Choose mode tmate (ubuntu)
        run: |
          # 获取输入的模式参数
          MODE=${{ github.event.inputs.mode || 'tmate' }}
          # 根据模式执行对应的脚本（相对路径）
          bash ./${MODE}2actions.sh
        shell: bash # 使用 Bash 作为脚本的执行环境
        
      # 第三步：休眠 6 小时
      - name: Sleep
        run: sleep 6h # 让作业保持运行状态以便调试
